### ISSUE TITLE
plugin 'siezi\phileAdmin' could not be loaded

### ISSUE THREAD

**Issue by rosewoodmarketing** [Schlaefer/phileAdmin#1]
- fresh PhileCMS install (latest download)
- no additional plugins installed
- no additional configuration other than "encryptionKey"
- download master branch of Schlaefer/phileAdmin
- extract to phile/plugins/phile
- rename folder to phileAdmin
- load domain.com/backend/
- same error message happens when trying to reach the home page also - can't load any pages
  ![untitled](https://cloud.githubusercontent.com/assets/12697794/7917028/573011a0-0855-11e5-89bd-80e11d812fd1.jpg)

**Comment by Schlaefer** [comment]
Hi.

The plugin must be placed into `plugins/siezi` (not `plugins/phile`). 

Currently the recommended way to installing it is using composer, this downloads everything and puts it into the right place. Otherwise you have to install all required third party libraries (Bootstrap, Silex, …) manually too.

**Comment by Schlaefer** [comment]
I've tried to come up with an easy way to provide a non-composer package. Try the archive on the [release page](https://github.com/Schlaefer/phileAdmin/releases) if you're inclined.

**Comment by rosewoodmarketing** [comment]
I'm on a quest to find something more lightweight and faster than Drupal for smaller sites. From what I read of Phile (and watched in the video on the home page) I really wanted to make Phile work.
- So I went ahead and figured out how to install Composer
- Then I had to enable several PHP functions
- And edit my PHP.ini
- Then needed to add another module to be able to edit pages

And after I was all done (plus messing with some additional modules), I realized the whole process was far from "stupidly simple", so I decided to move on. I'll keep my eye on Phile...it seems to have a lot going for it, but it doesn't fit for me right now.

Thanks for responding though...I appreciate it!

**Comment by Schlaefer** [comment]
Thanks for the feedback.

>   • So I went ahead and figured out how to install Composer
>   • Then I had to enable several PHP functions
>   • And edit my PHP.ini

The download on philecms.org should work without any of those steps necessary. Any common PHP installation should do. If you run into a specific issue feedback would be greatly appreciated.

>   • Then needed to add another module to be able to edit pages

Phile's main purpose is to serve existing content files. It isn't opinionated on how those files get there or how they are edited. This probably won't change.

> I realized the whole process was far from "stupidly simple"

That's what PicoCMS claims. PhileCMS is the "But you can change that". ;)

**Comment by rosewoodmarketing** [comment]
You're right, the Phile installation did go very easy (perfect). But this is an issue queue for the admin plugin and that's what my trouble was. Sorry if that wasn't clear. I ended up elaborating a little more on my situation but I was referring to the complex admin plugin installation (lots more dependencies than Phile has) and additional plugins needed to be able to use and edit pages in the admin interface (some installed with composer, some I uploaded, some didn't install properly, etc).

Thanks!

**Comment by Schlaefer** [comment]
> complex admin plugin installation (lots more dependencies than Phile has) and additional plugins

This is where composer really shines. With:

```
composer create-project phile-cms/phile --no-dev;
cd phile;
composer require siezi/phile-admin-markdown-editor --update-no-dev;
```

and activation in your config:

```
$config['plugins']['siezi\\phileAdmin']['active'] = true;
$config['plugins']['siezi\\phileAdminMarkdownEditor']['active'] = true;
```

you create a complete new Phile installation including the editor ready to go.

This is a zero star repository so far. That makes it hard to justify the effort to provide release packages, esp. when composer makes it so easy. But I understand your point. That's why Phile itself offers a release zip with all components included.

**Comment by rosewoodmarketing** [comment]
I probably shouldn't have used the term "dependencies". "Requirements" would have probably been appropriate.

What I was referring to is Composer is only for the "files" install. Composer has nothing to do with:
- Then I had to enable several PHP functions (missing xsl...enable and rebuild PHP...missing intl...enable and rebuild PHP again...)
- And edit my PHP.ini (requires proc_open - normally disabled in hosting accounts for security reasons)

This admin plugin needed all this to make it work. Phile did not need these extra steps. No other CMS I ever installed needed these (and I installed lots of CMSes). Hopefully I expressed that better now. :-)

**Comment by Schlaefer** [comment]
Ah, O.K. I misunderstood you completely.

All requirements should be readably available on shared hosting accounts. Just tested the installation above on strato and hostingeurope: upload and run. No problem. Those extension are usually enabled in a common PHP setup.

proc_open: I've no idea. Scanning the code it's not mentioned once in the source.

**Comment by nickbe** [comment]
I just run through the composer installation. With the EXACT same result as described in the beginning this post thread. So

**Comment by marcelloh** [comment]
I try this:
composer require siezi/phile-admin-markdown-editor --update-no-dev;
it goes wrong (--update-no-dev is not known)
without it it goes wrong too
```
Problem 1
    - Installation request for phile-cms/phile No version set (parsed as 1.0.0) -> satisfiable by phile-cms/phile[No version set (parsed as 1.0.0)].
    - siezi/phile-admin-markdown-editor 2.0.0 requires phile-cms/phile ^1.6.0 -> satisfiable by phile-cms/phile[1.6.0, 1.7.1].
    - Can only install one of: phile-cms/phile[1.6.0, No version set (parsed as 1.0.0)].
    - Can only install one of: phile-cms/phile[1.7.1, No version set (parsed as 1.0.0)].
    - Installation request for siezi/phile-admin-markdown-editor ^2.0 -> satisfiable by siezi/phile-admin-markdown-editor[2.0.0].
```
